# Lab 02: PyTorch 텐서 행렬곱 (Matrix Multiplication)

이 노트북에서는 PyTorch를 사용하여 다음을 수행합니다:
1. 3x3 크기의 랜덤 텐서 2개 생성
2. 두 텐서의 행렬곱 계산
3. 결과 텐서의 크기(shape)와 데이터 타입 출력

### prompt
1. PyTorch를 사용하여 3x3 크기의 랜덤 덴서 2개의 생성한다. 2. 두 센서의 행렬곱(Matric Multiplication)을 계산하는 간단한 코드를 짜줘. 3. 결과 텐서의 크기(shape)과 데이터 타입을 출력해줘 4. 최종 코드를 Lab02.ipynb로 저장해줘

In [1]:
# PyTorch 라이브러리 임포트
import torch

# 재현성을 위한 시드 설정 (선택사항)
torch.manual_seed(42)

## 1. 3x3 크기의 랜덤 텐서 2개 생성

`torch.rand()` 함수는 0과 1 사이의 균등분포(uniform distribution)에서 랜덤 값을 생성합니다.

In [2]:
# 첫 번째 3x3 랜덤 텐서 생성
tensor1 = torch.rand(3, 3)

# 두 번째 3x3 랜덤 텐서 생성
tensor2 = torch.rand(3, 3)

print("=" * 50)
print("첫 번째 텐서:")
print(tensor1)
print("\n두 번째 텐서:")
print(tensor2)
print("=" * 50)

첫 번째 텐서:
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408]])

두 번째 텐서:
tensor([[0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])


## 2. 두 텐서의 행렬곱(Matrix Multiplication) 계산

PyTorch에서 행렬곱을 수행하는 방법:
- `torch.matmul(tensor1, tensor2)` 함수 사용
- `@` 연산자 사용: `tensor1 @ tensor2`
- `torch.mm(tensor1, tensor2)` 함수 사용 (2D 텐서 전용)

**주의**: 요소별 곱셈(element-wise multiplication)은 `*` 연산자를 사용합니다.

In [3]:
# 행렬곱 계산 (방법 1: torch.matmul 사용)
result = torch.matmul(tensor1, tensor2)

# 또는 @ 연산자 사용 (방법 2)
# result = tensor1 @ tensor2

print("\n" + "=" * 50)
print("행렬곱 결과:")
print(result)
print("=" * 50)


행렬곱 결과:
tensor([[1.0774, 1.6830, 1.4215],
        [0.7253, 1.6503, 1.2036],
        [1.1281, 1.5234, 1.2804]])


## 3. 결과 텐서의 크기(shape)와 데이터 타입 출력

텐서의 주요 속성:
- `shape` 또는 `size()`: 텐서의 크기
- `dtype`: 데이터 타입 (예: float32, int64 등)
- `ndim`: 차원의 수
- `numel()`: 전체 요소의 개수

In [4]:
# 결과 텐서의 정보 출력
print("\n" + "=" * 50)
print("결과 텐서 정보:")
print(f"크기(Shape): {result.shape}")
print(f"크기(Size): {result.size()}")  # shape와 동일한 정보
print(f"데이터 타입(Data Type): {result.dtype}")
print(f"차원(Dimension): {result.ndim}")
print(f"전체 요소 개수: {result.numel()}")
print("=" * 50)


결과 텐서 정보:
크기(Shape): torch.Size([3, 3])
크기(Size): torch.Size([3, 3])
데이터 타입(Data Type): torch.float32
차원(Dimension): 2
전체 요소 개수: 9


## 추가 예제: 행렬곱 검증

행렬곱의 결과를 수동으로 계산하여 검증해봅시다.

In [5]:
# 첫 번째 행, 첫 번째 열의 값을 수동으로 계산
# result[0, 0] = tensor1[0, 0] * tensor2[0, 0] + tensor1[0, 1] * tensor2[1, 0] + tensor1[0, 2] * tensor2[2, 0]

manual_calculation = (
    tensor1[0, 0] * tensor2[0, 0] + 
    tensor1[0, 1] * tensor2[1, 0] + 
    tensor1[0, 2] * tensor2[2, 0]
)

print("\n" + "=" * 50)
print("행렬곱 검증:")
print(f"PyTorch 계산 결과 [0, 0]: {result[0, 0].item():.6f}")
print(f"수동 계산 결과 [0, 0]: {manual_calculation.item():.6f}")
print(f"차이: {abs(result[0, 0] - manual_calculation).item():.10f}")
print("=" * 50)


행렬곱 검증:
PyTorch 계산 결과 [0, 0]: 1.077418
수동 계산 결과 [0, 0]: 1.077418
차이: 0.0000000000


## 요약

이 노트북에서 배운 내용:
1. ✅ `torch.rand()`를 사용하여 랜덤 텐서 생성
2. ✅ `torch.matmul()` 또는 `@` 연산자로 행렬곱 수행
3. ✅ 텐서의 `shape`, `dtype` 등 주요 속성 확인

**핵심 포인트**:
- 행렬곱: `A @ B` (A의 열 수 = B의 행 수)
- 요소별 곱셈: `A * B` (같은 크기의 텐서)
- 3x3 행렬곱의 결과도 3x3 행렬