# Lab 02-01: PyTorch 텐서 Reshape (1차원 → 2차원)

이 노트북에서는 PyTorch를 사용하여 다음을 수행합니다:
1. 1차원 텐서 생성
2. 1차원 텐서를 2차원(행렬)로 변경 (reshape)

### Prompt
1. 주어진 1차원 텐서를 2차원(행렬)로 변경(reshape)하는 간단한 예제를 만들어줘 
2. 완성된 코드를 Lab02_01.ipynb 파일로 저장해줘

In [1]:
# PyTorch 라이브러리 임포트
import torch

# 재현성을 위한 시드 설정
torch.manual_seed(42)

## 1. 1차원 텐서 생성

`torch.arange()`를 사용하여 0부터 11까지의 정수를 가진 1차원 텐서를 생성합니다.

In [2]:
# 1차원 텐서 생성 (0부터 11까지의 정수, 총 12개 요소)
tensor_1d = torch.arange(12)

print("=" * 50)
print("원본 1차원 텐서:")
print(tensor_1d)
print(f"\n크기(Shape): {tensor_1d.shape}")
print(f"차원(Dimension): {tensor_1d.ndim}")
print(f"전체 요소 개수: {tensor_1d.numel()}")
print("=" * 50)

원본 1차원 텐서:
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

크기(Shape): torch.Size([12])
차원(Dimension): 1
전체 요소 개수: 12


## 2. 1차원 → 2차원 변환 (Reshape)

### 예제 1: 3행 4열로 변환

`reshape()` 메서드를 사용하여 12개의 요소를 3행 4열의 2차원 행렬로 변환합니다.

In [3]:
# 3행 4열로 변환
tensor_2d_3x4 = tensor_1d.reshape(3, 4)   # (행, 열) 크기의 2차원 텐서로 변환

print("\n" + "=" * 50)
print("2차원 텐서 (3행 4열):")
print(tensor_2d_3x4)
print(f"\n크기(Shape): {tensor_2d_3x4.shape}")
print(f"차원(Dimension): {tensor_2d_3x4.ndim}")
print(f"전체 요소 개수: {tensor_2d_3x4.numel()}")
print("=" * 50)


2차원 텐서 (3행 4열):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

크기(Shape): torch.Size([3, 4])
차원(Dimension): 2
전체 요소 개수: 12


### 예제 2: 4행 3열로 변환

같은 12개의 요소를 4행 3열로도 변환할 수 있습니다.

In [4]:
# 4행 3열로 변환
tensor_2d_4x3 = tensor_1d.reshape(4, 3)

print("\n" + "=" * 50)
print("2차원 텐서 (4행 3열):")
print(tensor_2d_4x3)
print(f"\n크기(Shape): {tensor_2d_4x3.shape}")
print(f"차원(Dimension): {tensor_2d_4x3.ndim}")
print("=" * 50)


2차원 텐서 (4행 3열):
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

크기(Shape): torch.Size([4, 3])
차원(Dimension): 2


### 예제 3: 자동 크기 추론 (-1 사용)

한 차원을 `-1`로 설정하면 PyTorch가 자동으로 크기를 계산합니다.

예: `reshape(3, -1)` → PyTorch가 자동으로 (3, 4)로 계산

In [5]:
# 3행으로 지정하고, 열은 자동 계산
tensor_2d_auto = tensor_1d.reshape(3, -1)

print("\n" + "=" * 50)
print("자동 크기 추론 (3, -1):")
print(tensor_2d_auto)
print(f"\n크기(Shape): {tensor_2d_auto.shape}")
print("\n설명: 12개 요소를 3행으로 나누면 자동으로 4열이 됩니다.")
print("=" * 50)


자동 크기 추론 (3, -1):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

크기(Shape): torch.Size([3, 4])

설명: 12개 요소를 3행으로 나누면 자동으로 4열이 됩니다.


## 3. 랜덤 텐서로 실습

실제 딥러닝에서 자주 사용하는 랜덤 값을 가진 텐서로 reshape를 연습해봅시다.

In [6]:
# 20개의 랜덤 값을 가진 1차원 텐서 생성
random_1d = torch.rand(20)

print("\n" + "=" * 50)
print("랜덤 1차원 텐서 (20개 요소):")
print(random_1d)
print(f"\n크기(Shape): {random_1d.shape}")
print(f"데이터 타입(Data Type): {random_1d.dtype}")
print("=" * 50)


랜덤 1차원 텐서 (20개 요소):
tensor([0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
        0.1332, 0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739,
        0.2666, 0.6274])

크기(Shape): torch.Size([20])
데이터 타입(Data Type): torch.float32


In [7]:
# 5행 4열로 변환
random_2d = random_1d.reshape(5, 4)

print("\n" + "=" * 50)
print("랜덤 2차원 텐서 (5행 4열):")
print(random_2d)
print(f"\n크기(Shape): {random_2d.shape}")
print(f"데이터 타입(Data Type): {random_2d.dtype}")
print("=" * 50)


랜덤 2차원 텐서 (5행 4열):
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274]])

크기(Shape): torch.Size([5, 4])
데이터 타입(Data Type): torch.float32


## 4. 결과 텐서의 정보 확인

변환된 2차원 텐서의 상세 정보를 확인합니다.

In [8]:
# 2차원 텐서의 상세 정보
print("\n" + "=" * 50)
print("2차원 텐서 상세 정보:")
print(f"크기(Shape): {tensor_2d_3x4.shape}")
print(f"크기(Size): {tensor_2d_3x4.size()}")  # shape와 동일
print(f"데이터 타입(Data Type): {tensor_2d_3x4.dtype}")
print(f"차원(Dimension): {tensor_2d_3x4.ndim}")
print(f"전체 요소 개수: {tensor_2d_3x4.numel()}")
print(f"\n행의 개수: {tensor_2d_3x4.shape[0]}")
print(f"열의 개수: {tensor_2d_3x4.shape[1]}")
print("=" * 50)


2차원 텐서 상세 정보:
크기(Shape): torch.Size([3, 4])
크기(Size): torch.Size([3, 4])
데이터 타입(Data Type): torch.int64
차원(Dimension): 2
전체 요소 개수: 12

행의 개수: 3
열의 개수: 4


## 요약

### ✅ 배운 내용:

1. **1차원 텐서 생성**:
   ```python
   tensor_1d = torch.arange(12)  # [0, 1, 2, ..., 11]
   ```

2. **2차원으로 변환 (Reshape)**:
   ```python
   tensor_2d = tensor_1d.reshape(3, 4)  # 3행 4열
   tensor_2d = tensor_1d.reshape(4, 3)  # 4행 3열
   tensor_2d = tensor_1d.reshape(3, -1) # 3행, 열은 자동 계산
   ```

3. **주요 규칙**:
   - 전체 요소 개수는 변경 전후가 동일해야 함
   - 12개 요소 → (3, 4), (4, 3), (2, 6), (6, 2) 등 가능
   - `-1` 사용 시 자동으로 크기 계산

### 🔑 핵심 코드:

```python
# 1차원 텐서 생성
tensor_1d = torch.arange(12)        # Shape: [12]

# 2차원으로 변환
tensor_2d = tensor_1d.reshape(3, 4) # Shape: [3, 4]

# 크기와 데이터 타입 확인
print(tensor_2d.shape)              # torch.Size([3, 4])
print(tensor_2d.dtype)              # torch.int64
```