# PyTorch Matrix Multiplication

이 노트북은 PyTorch를 사용하여 텐서를 생성하고 행렬 곱셈을 수행하는 예제입니다.

In [1]:
import torch

## 1. 3x3 크기의 랜덤 텐서 2개 생성

In [2]:
tensor1 = torch.rand(3, 3)
tensor2 = torch.rand(3, 3)

print("Tensor 1:\n", tensor1)
print("Tensor 2:\n", tensor2)

Tensor 1:
 tensor([[0.8994, 0.8689, 0.1514],
        [0.1904, 0.2837, 0.2939],
        [0.9212, 0.5250, 0.2525]])
Tensor 2:
 tensor([[0.1394, 0.6781, 0.4987],
        [0.7227, 0.0269, 0.3319],
        [0.3065, 0.5100, 0.2836]])


## 2. 두 텐서의 행렬곱(Matrix Multiplication) 계산

In [3]:
result = torch.matmul(tensor1, tensor2)

print("Result:\n", result)

Result:
 tensor([[0.7997, 0.7105, 0.7799],
        [0.3216, 0.2866, 0.2724],
        [0.5852, 0.7675, 0.7052]])


## 3. 결과 텐서의 크기(shape)과 데이터 타입 출력

In [4]:
print("Shape:", result.shape)
print("Data Type:", result.dtype)

Shape: torch.Size([3, 3])
Data Type: torch.float32
